### ISSUE TITLE
Create Landing Section

### ISSUE THREAD

**Issue by aryasoni98** [Feetwings/feetwings.github.io#3]
<img width="1659" alt="Screenshot 2021-06-15 at 7 59 06 PM" src="https://user-images.githubusercontent.com/18515597/122071316-45c2e380-ce14-11eb-9345-bfcb9731329e.png">

[**Download Assets**](https://github.com/Feetwings/feetwings.github.io/tree/main/assets/images)

**Comment by qw-erty** [comment]
hello this is abhinav,
Please assign this to me

**Comment by aryasoni98** [comment]
Yes sure , Go Head

**Comment by aryasoni98** [comment]
Complete
