### ISSUE TITLE
What Makes us special section

### ISSUE THREAD

**Issue by aryasoni98** [Feetwings/feetwings.github.io#4]
<img width="1655" alt="Screenshot 2021-06-15 at 8 05 50 PM" src="https://user-images.githubusercontent.com/18515597/122072503-427c2780-ce15-11eb-9552-156f54dce95e.png">

[**Download Assets**](https://github.com/Feetwings/feetwings.github.io/tree/main/assets/images)

**Comment by qw-erty** [comment]
please assign this to me
