### ISSUE TITLE
Bug: Change Download Button in Landing Page 

### ISSUE THREAD

**Issue by aryasoni98** [Feetwings/feetwings.github.io#41]
React version:

## Steps To Reproduce

1.
2.

Link to code example: ![Screenshot 2022-01-30 at 11 36 11 PM](https://user-images.githubusercontent.com/18515597/151711692-83b8f4d9-bbca-4d72-9906-8cdc29fb04e3.png)

**Comment by shubhamgupta9896** [comment]
fixed
